apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: thieryl/nginx:v0.1.3
        ports:
        - containerPort: 8080
